### ISSUE TITLE
Uncaught exception error on startup

### ISSUE THREAD

**Issue by marcinn2** [normen/homebridge-platform-maxcube#15]
Hi

I have a problem when starting homebridge with max plugin:

Uncaught exception error:  TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at Object.parseCommandMetadata (/usr/lib64/node_modules_max/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-commandparser.js:66:24)
    at Object.parse (/usr/lib64/node_modules_max/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-commandparser.js:20:35)
    at MaxCubeLowLevel.<anonymous> (/usr/lib64/node_modules_max/homebridge-platform-maxcube/node_modules/maxcube2/maxcube.js:53:46)
    at emitOne (events.js:116:13)
    at MaxCubeLowLevel.emit (events.js:211:7)
    at /usr/lib64/node_modules_max/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:43:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/lib64/node_modules_max/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:39:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

  node --version
v8.11.1

homebridge version 0.4.45

BR,

**Comment by jk** [comment]
Same here

**Comment by normen** [comment]
What version of the plugin are you using? Master? Or the npm release?

**Comment by normen** [comment]
Okay, should be fixed in the new version of the maxcube2 library, update your dependencies:

https://github.com/normen/maxcube2/commit/250d6fbeb4f3daa2b3ea94d6ecd78922a57da682

**Comment by jk** [comment]
Hmm looks like it didn't fix the issue:

```
homebridge_1  | Uncaught exception error:  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
homebridge_1  |     at Function.from (buffer.js:207:11)
homebridge_1  |     at Object.parseCommandMetadata (/homebridge/node_modules/maxcube2/maxcube-commandparser.js:66:31)
homebridge_1  |     at Object.parse (/homebridge/node_modules/maxcube2/maxcube-commandparser.js:20:35)
homebridge_1  |     at MaxCubeLowLevel.<anonymous> (/homebridge/node_modules/maxcube2/maxcube.js:53:46)
homebridge_1  |     at MaxCubeLowLevel.emit (events.js:182:13)
homebridge_1  |     at /homebridge/node_modules/maxcube2/maxcube-lowlevel.js:43:14
homebridge_1  |     at Array.forEach (<anonymous>)
homebridge_1  |     at Socket.<anonymous> (/homebridge/node_modules/maxcube2/maxcube-lowlevel.js:39:16)
homebridge_1  |     at Socket.emit (events.js:182:13)
homebridge_1  |     at addChunk (_stream_readable.js:283:12)
homebridge_1  |     at readableAddChunk (_stream_readable.js:264:11)
homebridge_1  |     at Socket.Readable.push (_stream_readable.js:219:10)
homebridge_1  |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Output of `npm list`

```
/homebridge # npm list
[…]
`-- homebridge-platform-maxcube@1.1.2
  `-- maxcube2@2.1.3
    +-- bluebird@3.5.3
    `-- moment@2.24.0 deduped
```

**Comment by normen** [comment]
Then it seems you're actually not getting any data in from the cube..
